### ISSUE TITLE
How to use it in dark mode. 

### ISSUE THREAD

**Issue by Srt9930** [Hamadakram/AlertView#12]
Hey! You made an amazing Library it's so rich.
So Thank you so much 🙇♥️
Now You mentioned in the code alert.setTheme(AlertView.DARK)
But when and where to place it ?

**Comment by VivekThummar52** [comment]
Are you asking for `alert.setTheme(AlertView.DARK)` which is mentioned in the main page of this repo(in `README` file), then you should take a look at project files or we can say in `MainActivity.kt` file and `activity_main.xml`.

**Comment by Srt9930** [comment]
@VivekThummar52 Thanks for your advice.
Well i have solved the problem by fork the project and it has merged successfully. I think i should close this issue.
